[project]
name = "evalobility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ddtrace>=4.1.1",
    "dotenv>=0.9.9",
    "ipykernel>=7.1.0",
]
